spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
      - id: api-1
        uri: lb://WELCOME-API
        predicates: 
          - Path=/welcome
      - id: api-2
        uri: lb://GREATING-API
        predicates: 
          - Path=/greating
server:
  port: 3333